-- Seeds mínimos de configuración sin secretos reales.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('a892fa5e-2880-5e4f-8a1c-c721f8ea9f52','core_identity.enabled','{"enabled":true,"source":"database/seeds/002_seed_system_settings.sql"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('63f1de16-44c4-5c83-a7de-1b8ec7531123','core_permissions.enabled','{"enabled":true,"source":"database/seeds/002_seed_system_settings.sql"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('b1d3af63-42b7-5b81-9e47-8f6540ab2765','core_modules.enabled','{"enabled":true,"source":"database/seeds/002_seed_system_settings.sql"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('1fd449c3-787c-59d6-849f-3b919d6bf10a','core_events.enabled','{"enabled":true,"source":"database/seeds/002_seed_system_settings.sql"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('d34bfc8f-c410-58bd-b338-87a06be4552d','core_doctor.readonly','{"readonly":true,"source":"database/seeds/002_seed_system_settings.sql"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('86b100e7-b85f-529a-aef2-ea8f0c15a4f6','ai_admin.enabled','{"enabled":false,"reason":"disabled_by_default"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
INSERT INTO `system_settings` (`id`,`key`,`value_json`,`scope`,`is_secret`,`created_at`,`updated_at`) VALUES ('e5253b25-fd28-5098-801c-752e439ea212','visible_features.enabled','{"enabled":false,"gate":"READY_FOR_VISIBLE_FEATURE_DEVELOPMENT"}','{"scope":"global"}',0,CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE `value_json`=VALUES(`value_json`), `updated_at`=CURRENT_TIMESTAMP(3);
COMMIT;
